jobs:
  test_then_deploy:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Deploy to github
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            npm run build
            cd build
            cp -a ../.circleci .
            git init
            git add .
            git commit -m "Deploy to Github Pages"
            git push --force --quiet "https://${GH_TOKEN}@github.com/jonbnewman/overfoc.us.git" master:gh-pages > /dev/null 2>&1
orbs:
  node: circleci/node@1.1
version: 2.1
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test_then_deploy:
          filters:
            branches:
              only:
                - master
